// src/devices/dto/index.ts
import { IsNotEmpty, IsOptional, IsString } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class RegisterDeviceDto {
  @ApiProperty({
    example: 'device-uuid-v4-here',
    description:
      'Unique identifier for this device installation — generated by the client app',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({
    example: 'MFkwEwYHKoZIzj0CAQY...',
    description:
      'ECDSA P-256 public key in base64url or PEM format — used to verify future device signatures',
  })
  @IsString()
  @IsNotEmpty()
  publicKey: string;

  @ApiPropertyOptional({
    example: 'iPhone 15 Pro — iOS 17.3',
    description: 'Human-readable device label for the device management screen',
  })
  @IsString()
  @IsOptional()
  deviceName?: string;
}
